include_guard(GLOBAL)

function(stm32_status_rule)
    message(STATUS "====================================================================================")
endfunction()

function(stm32_status_section title)
    stm32_status_rule()
    message(STATUS "${title}")
    stm32_status_rule()
endfunction()

function(stm32_require_existing_path label path_value)
    if("${path_value}" STREQUAL "")
        message(FATAL_ERROR "${label} is empty")
    endif()

    if(EXISTS "${path_value}")
        message(STATUS "${label}: ${path_value}")
    else()
        message(FATAL_ERROR "${label} not found: ${path_value}")
    endif()
endfunction()

function(stm32_join_and_print label)
    if(ARGN)
        list(JOIN ARGN ", " joined_items)
    else()
        set(joined_items "<none>")
    endif()

    message(STATUS "${label}: ${joined_items}")
endfunction()

function(stm32_print_configuration_summary)
    stm32_status_section("STM32F103 Build Configuration")
    message(STATUS "Project: ${PROJECT_NAME}")
    message(STATUS "Version: ${PROJECT_VERSION}")
    message(STATUS "Target: ${PROJECT_NAME}.elf")
    message(STATUS "MCU: ${MCU} (${MCU_CPU})")
    message(STATUS "Optimization: -O${OPTIMIZATION_LEVEL}")
    message(STATUS "Flash Address: ${FLASH_ADDRESS}")
    message(STATUS "Save Temps: ${SAVE_TEMPS}")
    message(STATUS "Build Output: ${BUILD_OUTPUT_DIR}")
    message(STATUS "Binary Output: ${BINARY_FILE}")
    message(STATUS "HEX Output: ${HEX_FILE}")
    stm32_join_and_print("Driver Modules" ${DRIVER_MODULES})
    message(STATUS "Driver Tree View: ${DRIVER_MODULE_TREE}")
    message(STATUS "Helper Targets: flash, flash_uart, debug, clean_all, info, erase_flash")
endfunction()

function(stm32_print_source_summary)
    list(LENGTH PROJECT_SOURCES project_source_count)
    list(LENGTH CORE_SOURCES core_source_count)
    list(LENGTH SELECTED_DRIVER_SOURCES driver_source_count)
    list(LENGTH SELECTED_DRIVER_INCLUDES driver_include_count)

    stm32_status_section("Source Summary")
    message(STATUS "Project Sources: ${project_source_count}")
    message(STATUS "Driver Sources: ${driver_source_count}")
    message(STATUS "Driver Include Dirs: ${driver_include_count}")
    message(STATUS "Core Sources: ${core_source_count}")
    message(STATUS "Total Sources: ${project_source_count} + ${driver_source_count} + ${core_source_count}")
endfunction()
